package aqbitig.gizehter.view;

import aqbitig.gizehter.controller.AbstractTree;
import aqbitig.gizehter.model.MyAtomic;
import aqbitig.lib.basic.T;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreePath;

/**
 * gizehter = giz(li) + anahtar
 *
 * @author aqdaycuklu
 */
public class SplitPane extends javax.swing.JPanel {

    private final aqbitig.gizehter.controller.AbstractTree abstractTree;

    public SplitPane(String mode, java.io.File file, String password) {
        T.o("splitpane");

        abstractTree = new AbstractTree() {
            @Override
            public void leafSelected() {
                info.clear();

                TreePath path = jTree.getSelectionPath();
                System.out.println(path.toString());

                TreeNode node = (TreeNode) path.getLastPathComponent();
                System.out.println(node);

                DefaultMutableTreeNode j = (DefaultMutableTreeNode) (path.getLastPathComponent());
                if (j.isLeaf() && !j.getAllowsChildren() && j.getUserObject() instanceof MyAtomic) {
                    MyAtomic m = (MyAtomic) j.getUserObject();
                    T.o(m.getLogin());
                    info.setNode(m);
                } else if (j.isLeaf() && !j.getAllowsChildren()) {
                    MyAtomic m = new MyAtomic();
                    j.setUserObject(m);
                    info.setNode(m);
                }
            }
        };
        abstractTree.setFile(file);
        abstractTree.setFilePath(file.getPath());
        abstractTree.setMode(mode);
        abstractTree.setPassword(password);
        abstractTree.setKey(password);
        initComponents();
        T.o("sp width: " + jSplitPane1.getSize().getWidth());
        setSize(500, 350);
        jSplitPane1.setDividerLocation(200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        info = new aqbitig.gizehter.view.Info(this);
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new aqbitig.gizehter.view.Tree(abstractTree);

        jSplitPane1.setDividerLocation(395);
        jSplitPane1.setDividerSize(10);
        jSplitPane1.setResizeWeight(0.5);
        jSplitPane1.setMinimumSize(new java.awt.Dimension(500, 350));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(500, 350));
        jSplitPane1.setRightComponent(info);

        jScrollPane1.setViewportView(jTree);

        jSplitPane1.setLeftComponent(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public Info getInfo() {
        return info;
    }

    public void setInfo(Info info) {
        this.info = info;
    }

    public JTree getjTree() {
        return jTree;
    }

    public void setjTree1(JTree jTree) {
        this.jTree = jTree;
    }

    public javax.swing.JSplitPane getSplitPane() {
        return this.jSplitPane1;
    }

    public javax.swing.JScrollPane getjScrollPane() {
        return jScrollPane1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private aqbitig.gizehter.view.Info info;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTree jTree;
    // End of variables declaration//GEN-END:variables
}
